/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pqtip;
import org.junit.Assert;
import org.junit.Test;
import pqtip.cipher_suite.PrototypeCipherSuiteProvider;
import pqtip.connection.BlockingSocketAdapter;
import pqtip.connection.PQTIPConnection;
import pqtip.protocol.ConnectionFactory;

import java.io.Console;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

import static org.junit.Assert.*;

public class PqtipDemo {
    public static void main(String[] args) throws IOException, InterruptedException {
        var demo = new PqtipDemo();
        demo.testExchange();
    }
     public void testExchange() throws IOException, InterruptedException {
        var message = "Pqtip placeholder message";
        this.runServer(message);
        Thread.sleep(1000);
        var factory = new ConnectionFactory(new PrototypeCipherSuiteProvider());
        long start = System.nanoTime();

        var client = new Socket("127.0.0.1", 8787);
        var encClient = factory.secureClientConnection(new BlockingSocketAdapter(client));
        encClient.send(message.getBytes());
        //System.out.println(String.format("Run %d: executed in %d nanoseconds", 1, duration));
        var data = encClient.receive();
        System.out.println(String.format("[Client] Received %d bytes of data", data.length));
        System.out.println(String.format("[Client] Received message: %s", new String(data)));
        Assert.assertEquals(new String(data), message);
        client.close();

    }

    private void runServer(String message) throws IOException {
        new Thread(() -> {
            try {
                var serverSocket = new ServerSocket(8787);
                var factory = new ConnectionFactory(new PrototypeCipherSuiteProvider());
                while(true) {
                    var clientSocket = serverSocket.accept();
                    var encryptedSocket = factory.secureServerConnection(new BlockingSocketAdapter(clientSocket));
                    var data = encryptedSocket.receive();
                    System.out.println(String.format("[Server] Received %d bytes of data", data.length));
                    System.out.println(String.format("[Server] Received message: %s", new String(data)));
                    Assert.assertEquals(new String(data), message);
                    encryptedSocket.send(data);
                    clientSocket.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
    }
}
